config/routes.rb
Rails.application.routes.draw do
  resources :users
  resources :websites
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'users#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
end

app/models/website.rb
class Website < ApplicationRecord
  # def use_database
  #   ActiveRecord::Base.establish_connection(website_connection)
  # end
  #
  # # Revert back to the shared database
  # def revert_database
  #   ActiveRecord::Base.establish_connection(default_connection)
  # end
  #
  # private
  #
  # # Regular database.yml configuration hash
  # def default_connection
  #   binding.pry
  #   @default_config ||= ActiveRecord::Base.connection.instance_variable_get("@config").dup
  # end
  #
  # # Return regular connection hash but with database name changed
  # # The database name is a attribute (column in the database)
  # def website_connection
  #   default_connection.dup.update(:database => name)
  # end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :set_database

  helper_method :current_website

  # I use the entire domain, just change to find_by_subdomain and pass only the subdomain
  def current_website
    subdomain ||= request.subdomain
  end

  def set_database
    subdomain = current_website
    subdomain.present? ? Multidata::Application.use_database(subdomain) : Multidata::Application.revert_database
  end

  # Bonus - add view_path
  def set_paths
    self.prepend_view_path current_website.view_path unless current_website.view_path.blank?
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name)
    end
end

app/controllers/websites_controller.rb
class WebsitesController < ApplicationController
  before_action :set_website, only: [:show, :edit, :update, :destroy]

  # GET /websites
  # GET /websites.json
  def index
    @websites = Website.all
  end

  # GET /websites/1
  # GET /websites/1.json
  def show
  end

  # GET /websites/new
  def new
    @website = Website.new
  end

  # GET /websites/1/edit
  def edit
  end

  # POST /websites
  # POST /websites.json
  def create
    @website = Website.new(website_params)

    respond_to do |format|
      if @website.save
        format.html { redirect_to @website, notice: 'Website was successfully created.' }
        format.json { render :show, status: :created, location: @website }
      else
        format.html { render :new }
        format.json { render json: @website.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /websites/1
  # PATCH/PUT /websites/1.json
  def update
    respond_to do |format|
      if @website.update(website_params)
        format.html { redirect_to @website, notice: 'Website was successfully updated.' }
        format.json { render :show, status: :ok, location: @website }
      else
        format.html { render :edit }
        format.json { render json: @website.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /websites/1
  # DELETE /websites/1.json
  def destroy
    @website.destroy
    respond_to do |format|
      format.html { redirect_to websites_url, notice: 'Website was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_website
      @website = Website.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def website_params
      params.require(:website).permit(:name, :subdomain)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/websites_helper.rb
module WebsitesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Multidata</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>

app/views/websites/_form.html.erb
<%= form_with(model: website, local: true) do |form| %>
  <% if website.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(website.errors.count, "error") %> prohibited this website from being saved:</h2>

      <ul>
      <% website.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :subdomain %>
    <%= form.text_field :subdomain %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/websites/edit.html.erb
<h1>Editing Website</h1>

<%= render 'form', website: @website %>

<%= link_to 'Show', @website %> |
<%= link_to 'Back', websites_path %>

app/views/websites/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Websites</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Subdomain</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @websites.each do |website| %>
      <tr>
        <td><%= website.name %></td>
        <td><%= website.subdomain %></td>
        <td><%= link_to 'Show', website %></td>
        <td><%= link_to 'Edit', edit_website_path(website) %></td>
        <td><%= link_to 'Destroy', website, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Website', new_website_path %>

app/views/websites/new.html.erb
<h1>New Website</h1>

<%= render 'form', website: @website %>

<%= link_to 'Back', websites_path %>

app/views/websites/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @website.name %>
</p>

<p>
  <strong>Subdomain:</strong>
  <%= @website.subdomain %>
</p>

<%= link_to 'Edit', edit_website_path(@website) %> |
<%= link_to 'Back', websites_path %>